version: '3.1'

services:

  api:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: apis
      DB_USER: postgres
      DB_PASSWORD: secret
#      API_DB_PASSWORD_FILE: /run/secrets/db_password
#    secrets:
#      - db_password

  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_DB: apis
      PGUSER: postgres
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/apis_data



#define variables and provide file to populate their values
#secrets:
#  db_root_password:
#    file: ./db/db_root_password.txt
#  db_password:
#    file: ./db/db_password.txt

volumes:
  db_data: