version: '3.1'

services:
  db:
    image: mysql:8.1.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tibia
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
#      MYSQL_ROOT_PASSWORD: "pass"
      #inject these secrets into container
    secrets:
      - db_root_password
      - db_password
    expose:
      - 3306

  api:
    depends_on:
      - db
    image: golang:1.19
    ports:
      - "8080:80"
    environment:
      API_DB_HOST: db:3306
      API_DB_USER: user
      API_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

#define variables and provide file to populate their values
secrets:
  db_root_password:
    file: internal/db/db_root_password.txt
  db_password:
    file: internal/db/db_password.txt


volumes:
  db_data: