basePath: /
consumes:
    - application/json
info:
    description: '# Documentation of Player API'
    title: of Player API
    version: 1.0.0
paths: {}
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
